update schema-pg.sql for fixing missing dependency table.
ERROR:  conflicting NULL/NOT NULL declarations for column "host_id" of table "dependency"
LINE 3: ...INT NOT NULL REFERENCES "host"("id") ON DELETE CASCADE NULL,